image: rambabusaravanan/firebase
variables:
  DOCKER_DRIVER: overlay2
stages:
  - deploy
cache:                  
  paths:                
    - node_modules/     
  key: "$CI_BUILD_REPO" 
deploy-prod:
  stage: deploy
  only:
    - master
  script:
    - npm install
    - npm run build
    - firebase deploy --token "$FIREBASE_TOKEN"
