image: anoun/firebase
variables:
  DOCKER_DRIVER: overlay2
stages:
  - deploy
cache:                  
  paths:                
    - node_modules/     
  key: "$CI_BUILD_REPO" 
deploy-prod:
  stage: deploy
  only:
    - master
  script:
    - npm install
    - npm run build
    - firebase use default --token $FIREBASE_TOKEN
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN
