image: node:latest

cache:
  paths:
    - node_modules/
variables:
  DOCKER_DRIVER: overlay2
  
deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - npm install -g firebase-tools
    - npm install
    - npm run build
    - firebase deploy --token "$FIREBASE_TOKEN"